/* global MFF */
MFF.UNIFORMS.DATA =
{
 "aaou" : "Avengers: Age of Ultron",
 "aaou_blast" : "Avengers: Age of Ultron (blast)",
 "aaou_combat" : "Avengers: Age of Ultron (combat)",
 "aaou_speed" : "Avengers: Age of Ultron (speed)",
 "annihilation" : "Annihilation",
 "armored" : "Armored",
 "an" : "All-new",
 "anad" : "All-new, All-different",
 "anca" : "All-new Captain America",
 "ati" : "Avengers: The initiative",
 "attilanrising" : "Inhumans: Attilan rising",
 "avengers" : "The avengers",
 "ca" : "Captain America",
 "ca_75" : "Captain America 75th anniversary",
 "cacw" : "Captain America: Civil war",
 "capdoc" : "Capdoc",
 "catfa" : "Captain America: The first avenger",
 "catws" : "Captain America: The winter soldier",
 "classic" : "Classic",
 "classic_70" : "70's classic",
 "claws" : "Claws",
 "doc_strange" : "Doctor Strange",
 "dohk" : "Devil of Hell's kitchen",
 "gg" : "Guardians of the galaxy",
 "hda" : "Heavy duty armor",
 "ha" : "Heroic age",
 "howling" : "The howling commandos of S.H.I.E.L.D.",
 "infinity" : "Infinity",
 "iar" : "Inhumans : Attilan rising",
 "ip" : "Iron Patriot",
 "karachi" : "Karachi costume",
 "ll" : "Lady Loki",
 "mam" : "Marvel's Ant-man",
 "maos" : "Marvel's agents of S.H.I.E.L.D.",
 "maosq" : "Marvel's agents of S.H.I.E.L.D. (Quake)",
 "md" : "Marvel's Daredevil",
 "mif" : "Marvel's Iron Fist",
 "mlc" : "Marvel's Luke Cage",
 "modern" : "Modern",
 "modern2" : "Modern",
 "ms_marvel" : "Ms. Marvel",
 "na" : "New Avengers",
 "noir" : "Noir",
 "now" : "Marvel now!",
 "prometheus" : "Prometheus",
 "sa" : "Space armor",
 "spidoc" : "Spidoc",
 "ssm" : "Superior Spider-man",
 "sw_armor_wars" : "Secret wars: Armor wars",
 "sw_a_force" : "Secret wars: A-force",
 "sw_carol_corp" : "Secret wars: Captain Marvel & The Carol corp",
 "sw_future" : "Secret wars: Future imperfect",
 "sw_red_skull" : "Secret wars: Red skull",
 "sw_renew" : "Secret wars: Renew your vows",
 "sw_thors" : "Secret wars: Thors",
 "sw_zombies" : "Secret wars: Marvel zombies",
 "sw_1602" : "Secret wars: 1602 witch hunter angela",
 "sw_1872" : "Secret wars: 1872",
 "sw_2099" : "Secret wars: 2099",
 "tah" : "Totally awesome Hulk",
 "ttdw" : "Thor: The dark world",
 "ultimate" : "Ultimate",
 "unleashed" : "Monsters unleashed!",
 "unworthy" : "Unworthy",
 "websuit" : "Web suit",
 "wj" : "War journal",
 "warofking" : "War of king",
 "wwh" : "World War Hulk"
};
